# Site
title:              Josué Romero
bio:                'A student from UNIMINUTO'
description:        "Don't follow your dream, follow me!"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/BackGround.jpg'
tiled_bg:           false
locale:             es_CO
url:                https://josuerom.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
email:              josueromram3@gmail.com
twitter:            josueromr
facebook:           josueromr
github-url:         josuerom
instagram:          josueromram
codeforces:         josuerom
#stackoverflow:     123456/josueromr   from a "http://stackoverflow.com/users/123456/josueromr" link
#linkedin:          josueromr
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#youtube:           username
#youtube-channel:   channel
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
